AWSTemplateFormatVersion: "2023-10-16"
Description: "MSK Application Creation"

service: msk-test
provider:
  name: aws
  runtime: modejs16.x
  region: us-west-2
  stackName: test-msk-deployment

resources:
  Resources:
    MyKafkaTopic:
      Type: 'AWS::MSK::Cluster'
      Properties:
        ClusterName: MyKafkaCluster
        KafkaVersion: '2.7.0'
        NumberOfBrokerNodes: 2
        EncryptionInfo:
          EncryptionInTransit:
            InCluster: true
          EncryptionAtRest:
            #DataVolumeKMSKeyId: arn:aws:kms:us-west-2:123456789012:key/abcd1234-5678-90ab-cdef-1234567890ab
            DataVolumeKMSKeyId: arn:aws:kms:us-west-2:2128-8797-2892:key/655616de-d890-4008-9cb5-3c790287d43f
        BrokerNodeGroupInfo:
          BrokerAZDistribution: DEFAULT
          InstanceType: kafka.t3.small
          SecurityGroups:
          - 'sg-0bc940dd3c605d4b5'
          - 'sg-0bc940dd3c605d4b5'
          StorageInfo:
            EBSStorageInfo:
              VolumeSize: 100
          ClientSubnets:
          - 'subnet-01495913df919c8dd'
          - 'subnet-0cc596ef2758680d2'
              
