Parameters:
  Env:
    Type: String
    Description: dev
  ClusterName:
    Type: String
    Description: msk-cluster-persona
  BrokerInstanceType:
    Type: String
    Default: "kafka.t3.small"
  NumberOfBrokerNodes:
    Type: Number
    Default: 2
  VpcId:
    Type: String
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  KafkaVersion:
    Type: String
  ClusterType:
    Description: Please select Cluster Type
    Type: String
    ConstraintDescription: Can contain only ASCII characters.
    AllowedValues:
      - Provisioned
      - Serverless
  ConfigName:
    Type: String
    Description: Name of the MSK Configuration
  ServerProperties:
    Type: String
    Description: server.properties
  key1:
    Type: String
  key2:
    Type: String
  value1:
    Type: String
  value2:
    Type: String
     


Resources: 
  MSKConfiguration:
    Type: AWS::MSK::Configuration
    Properties:
      Name: !Ref ConfigName
      Description: "My MSK Configuration"
      ServerProperties: !Ref ServerProperties

  MSKClusterLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupClass: STANDARD
      LogGroupName: !Sub "/aws/kafka/${ClusterName}"
      RetentionInDays: 1
      
  MSKCluster:
    Type: "AWS::MSK::Cluster"
    Properties:
      ClusterName: !Sub "${ClusterName}-${Env}"
      BrokerNodeGroupInfo:
        InstanceType: !Ref BrokerInstanceType
        ClientSubnets: !Ref SubnetIds
      NumberOfBrokerNodes: !Ref NumberOfBrokerNodes
      KafkaVersion: !Ref KafkaVersion
      EncryptionInfo:
        EncryptionInTransit:
          InCluster: true
          ClientBroker: TLS
      EnhancedMonitoring: "PER_TOPIC_PER_BROKER"
      OpenMonitoring:
        Prometheus:
          JmxExporter:
            EnabledInBroker: 'true'
          NodeExporter:
            EnabledInBroker: 'true'  
      ConfigurationInfo:
        Arn: !GetAtt MSKConfiguration.Arn
        Revision: 1  
      LoggingInfo:
        BrokerLogs:
          CloudWatchLogs:
            Enabled: true
            LogGroup: !Sub /aws/kafka/${ClusterName}
      ClientAuthentication:
        Sasl:
          Iam:
            Enabled: true
      Tags:
        key1: !Sub ${key1}
        value2: !Sub ${value1}
        key2: !Sub ${key2}
        value2: !Sub ${value2}
