name: Deploy MSK
on:
  workflow_dispatch:
  #push:
   # branches:
    #  - pbd-infra
jobs:
  deploy:
    name: msk deploy
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      #- name: msk Deploy....
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY}}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_KEY}}"
          aws-region: us-west-2
          # role-to-assume: ""
          # role-duration-seconds: 3600
          # role-session-name: GitHubActions
      - name: user node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.20.0
      - run: npm install -g serverless
      - run: npm install serverless-plugin-resource-tagging
      
        name: Deploy Serverless Function
      - run: serverless deploy -c /home/runner/work/pbd/pbd/msk-serverless.yml
