name: Deploy topic on cluster stack

on:
  workflow_dispatch:

jobs:
  deploy:
    name: run shell script to create topic
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_KEY }}"
          aws-region: "${{ vars.AWS_REGION }}"
          role-to-assume: "${{ vars.AWS_DEPLOYMENT_ROLE }}"
          #role-to-assume: "developer"
          role-duration-seconds: 3600
          role-session-name: GithubActions      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: pwd
      - run: ls -l 
      - run: chmod 777 util/create_topic.sh
      - run: util/create_topic.sh topics.csv b-2.azpersona4dev.rwpi61.c2.kafka.us-west-2.amazonaws.com:9098,b-1.azpersona4dev.rwpi61.c2.kafka.us-west-2.amazonaws.com:9098 
    
      
