name: Deploy topic on cluster stack

on:
  workflow_dispatch:

jobs:
  deploy:
    name: run shell script to create topic
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - run: pwd
      - run: ls -l 
      - run: chmod 777 util/create_topic.sh
      - run: util/.\create_topic.sh topics.csv b-2.azpersona4dev.rwpi61.c2.kafka.us-west-2.amazonaws.com:9098,b-1.azpersona4dev.rwpi61.c2.kafka.us-west-2.amazonaws.com:9098 
    
      
