name: Deploy topic on cluster stack

on:
  workflow_dispatch:

jobs:
  deploy:
    name: run shell script to create topic
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_KEY }}"
          aws-region: "${{ vars.AWS_REGION }}"
          role-to-assume: "${{ vars.AWS_DEPLOYMENT_ROLE }}"
          #role-to-assume: "developer"
          role-duration-seconds: 3600
          role-session-name: GithubActions      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: pwd
      - run: ls -l 
      - run: chmod 777 util/create_topic.sh
      - run: curl -O https://archive.apache.org/dist/kafka/2.8.0/kafka_2.13-2.8.0.tgz
      - run: tar -xzf kafka_2.13-2.8.0.tgz
      - run: ls -al
      - run: ls -al kafka_2.13-2.8.0/bin/
      - run: aws kafka get-bootstrap-brokers --cluster-arn arn:aws:kafka:us-west-2:212887972892:cluster/az-persona4-dev/95146d5b-4693-4f1b-a778-1f07fc018ae1-2
      # run: ./create_topics1.sh '${{vars.CONFIG_FILE}}' util/topics.csv"
      - run: util/create_topic.sh util/topics.csv b-1.azpersona4dev.wgi9ny.c2.kafka.us-west-2.amazonaws.com:9098,b-2.azpersona4dev.wgi9ny.c2.kafka.us-west-2.amazonaws.com:9098 --command-config util/topic-config.properties 
      #- run: util/create_topic.sh util/topics.csv b-1.azpersona4dev.wgi9ny.c2.kafka.us-west-2.amazonaws.com,b-2.azpersona4dev.wgi9ny.c2.kafka.us-west-2.amazonaws.com 
    
      
