name: Manual Workflow for msk

on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_KEY }}"
          aws-region: "${{ vars.AWS_REGION }}"
          role-to-assume: "${{ vars.AWS_DEPLOYMENT_ROLE }}"
          #role-to-assume: "developer"
          role-duration-seconds: 3600
          role-session-name: GithubActions      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install serverless-plugin-resource-tagging
     
      - run: pwd
      - run: ls -l
      - run: aws cloudformation create-stack --stack-name "${{ vars.STACK_NAME }}" --template-body "file://${{ vars.YAML_FOLDER }}/msk-pbd.yaml" --parameters "file://${{ vars.JSON_FOLDER }}/msk-pbd.json"
    
      
