name: Manual2 Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Manual Workflow
      run: |
        echo "check present working directory"
        sudo pwd
