name: Deploy topic on cluster stack

on:
  workflow_dispatch:
    inputs:
        environment:
            type: choice
            description: " test.."
            options:
                - test
                - dev
                - preprod
                - prod
            required: true
            default: 'dev'
        Opeartion:
            type: choice
            description: " test.."
            options:
                - test
                - dev
                - preprod
                - prod
            required: true
            default: 'dev'
          confirm:
            type: boolean
            description: "test.." 
            required: true
            default: false       
        
    
  

jobs:
  deploy:
    name: run shell script to create topic
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment}}

    steps:
     
      - name: print TEST value
        run: echo "${{ vars.TEST }}"
      
