name: Deploy topic on cluster stack

on:
  workflow_dispatch:
    inputs:
        environment:
            type: choice
            description: " test.."
            options:
                - test
                - dev
                - preprod
                - prod
            required: true
            default: 'dev'
        confirm:
            type: boolean
            description: "test.." 
            required: true
            default: false       


jobs:
  deploy:
    name: run shell script to create topic
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment}}

    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_KEY }}"
          aws-region: "${{ vars.AWS_REGION }}"
          role-to-assume: "${{ vars.AWS_DEPLOYMENT_ROLE }}"
          #role-to-assume: "developer"
          role-duration-seconds: 3600
          role-session-name: GithubActions      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: print TEST value
        run: echo "${{ vars.TEST }}"
      
